require 'faker'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Character.destroy_all

u1 = User.create(username: "Peter")
u2 = User.create(username: "Junaid")
u3 = User.create(username: "Sean")
u4 = User.create(username: "Natany")
u5 = User.create(username: "Nick")
u6 = User.create(username: "Errol")

char1 = Character.create!(name: "Krusk", gender: "male", background: "Gladiator", race: "half-orc", strength: 13, dexterity: 11, constitution: 10, intelligence: 7, wisdom: 8, charisma: 4, picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk16ltQOHaU30iGu3BKGPDlAExA9VNwKRSE4z8YPC2ecbpnGvL", user_id: u1.id)
char2 = Character.create!(name: "Gimble", gender: "male", background: "Entertainer", race: "bard", strength: 3, dexterity: 7, constitution: 8, intelligence: 13, wisdom: 12, charisma: 15, picture: "https://i1.wp.com/www.allthingsdnd.com/wp-content/uploads/2018/03/GnomeBard.png?fit=822%2C1089&ssl=1",  user_id: u2.id)
char3 = Character.create!(name: "Vadania", gender: "female", background: "Pirate", race: "half-elf", strength: 10, dexterity: 11, constitution: 12, intelligence: 13, wisdom: 8, charisma: 10, picture: "https://66.media.tumblr.com/33819a6856b3d839e92d894a20ad2b2f/tumblr_p7rbxcLZnw1qf2swbo1_400.png", user_id: u3.id)
char4 = Character.create!(name: "Soveliss", gender: "male", background: "Gambler", race: "elf", strength: 9, dexterity: 12, constitution: 13, intelligence: 9, wisdom: 8, charisma: 11, picture: "https://66.media.tumblr.com/6c6af8f9a1367488056fa9c5668e7f76/tumblr_inline_ox2d8zLuit1qdq19t_540.jpg", user_id: u4.id)
char5 = Character.create!(name: "Ember", gender: "female", background: "Smuggler", race: "human", strength: 6, dexterity: 8, constitution: 10, intelligence: 14, wisdom: 9, charisma: 13, picture: "https://66.media.tumblr.com/dd687f7bc2ccbd54d41ffccf563c0683/tumblr_inline_oj971u6zRn1uudcoe_640.jpg", user_id: u5.id)
char6 = Character.create!(name: "Lidda", gender: "female", background: "Hermit", race: "halfling", strength: 3, dexterity: 6, constitution: 6, intelligence: 9, wisdom: 11, charisma: 10, picture: "https://img00.deviantart.net/64db/i/2016/343/5/a/scarred_lands__halfling_by_willobrien-dar3hwj.jpg", user_id: u6.id)
char7 = Character.create!(name: "Tagar", gender: "male", background: "Folk Hero", race: "Dragonborn", strength: 10, dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://i.pinimg.com/originals/b2/a4/96/b2a49646ac9a08d29c1c29e6ebdd1da5.jpg", user_id: u1.id)
char8 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Inheritor", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://i.pinimg.com/originals/b2/a4/96/b2a49646ac9a08d29c1c29e6ebdd1da5.jpg", user_id: u3.id)
char9 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Acolyte", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://i.pinimg.com/originals/d5/b4/fb/d5b4fb920d7f27ae22209ee2a83f1e80.jpg", user_id: u4.id)
char10 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Anthropologist", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://www.google.com/search?q=dnd+character+pictures&rlz=1C5CHFA_enUS847US847&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjuw7qOhKvjAhXXWM0KHb1gBXMQ_AUIECgB&biw=1920&bih=1001&dpr=1#imgrc=PhJCqv95CJeKVM:", user_id: u5.id)
char11 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Charlatan", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://cdnb.artstation.com/p/assets/covers/images/001/313/397/medium/andre-sutherland-swordsmanfinal.jpg?1444169885", user_id: u6.id)
char12 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Clan Crafter", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://a.wattpad.com/cover/156777832-352-k789116.jpg", user_id: u1.id)
char13 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Courtier", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://i.kinja-img.com/gawker-media/image/upload/s--2BuS3KEj--/c_scale,f_auto,fl_progressive,q_80,w_800/dt3zmraefxn1mxp6uhml.png", user_id: u2.id)
char14 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Criminal/Spy", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://kirileonard.com/wp-content/uploads/2018/05/kiri_leonard_vetis_web.jpg", user_id: u3.id)
char15 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Dimir Operative", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://d3idt3y1vhsqn9.cloudfront.net/wp-content/uploads/2013/01/01144807/revenant_color.jpg", user_id: u4.id)
char16 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Faction Agent", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://i.imgur.com/VrFBUBk.jpg", user_id: u5.id)
char17 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Far Traveler", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://2static.fjcdn.com/pictures/Dank+dd+character+concept+art+10+mentionlist+dndcharartpart1+channeldungeonsndragsdank+d+d+chara+cter+concept+artgjxiltw_538ddf_5931853.jpg", user_id: u6.id)
char18= Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Haunted One", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://cdnb.artstation.com/p/assets/images/images/009/732/273/large/christopher-lauto-phil-s-character.jpg?1520576538", user_id: u1.id)
char19= Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Izzet Engineer", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://s3.amazonaws.com/artistsnclients/hk6/samples/m92_800.jpg", user_id: u2.id)
char20 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Knight", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/101/642/420/618/636508498805912769.png", user_id: u3.id)
char21 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Marine", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://i.imgur.com/9Xf3GxY.jpg", user_id: u4.id)
char22= Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Noble", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://ksr-ugc.imgix.net/assets/021/878/484/092d6a675ea2af2f3e5429cdcb57709b_original.png?ixlib=rb-2.1.0&crop=faces&w=1552&h=873&fit=crop&v=1531929383&auto=format&frame=1&q=92&s=35fdab865b7e99c5391a307d99132f7d", user_id: u5.id)
char23= Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Plaintiff", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://d3idt3y1vhsqn9.cloudfront.net/wp-content/uploads/2016/01/25144928/eeveelutions-dnd-pokemon-gijinkas-02.jpg", user_id: u6.id)
char24 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Rival Intern", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://www.seekpng.com/png/detail/156-1568612_dwarf-paladin-dnd-dwarf-dnd-characters-fantasy-characters.png", user_id: u1.id)
char25 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Sage", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto/gigs/86073321/original/13e4081258fb68910b7a84d94df7e548b14fb3df/draw-your-dnd-character.png", user_id: u2.id)
char26 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Soldier", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://i.pinimg.com/736x/4a/2a/33/4a2a33c4e6380cfce334dcd8d600506d.jpg", user_id: u3.id)
char27 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Urban Bounty Hunter", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "http://nerdologists.com/wp-content/uploads/2017/12/Druid.png", user_id: u4.id)
char28= Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Waterdhavian Noble", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://media.wizards.com/2015/images/dnd/resources/Drow_Rogue.jpg", user_id: u5.id)
char29 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Uthgardt Tribe Member", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://i.pinimg.com/originals/a6/79/80/a67980a7d618d399ad16c9c791782f42.png", user_id: u6.id)
char30 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Orzhov Representative", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://media-waterdeep.cursecdn.com/avatars/thumbnails/7/641/420/618/636287076637981942.png", user_id: u1.id)
char31= Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "Mercenary Veteran", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://pinimg.icu/wall/0x0/roleplaygame-npg-charachters-dungeons-and-dragons-characters-dnd-characters-E3551c937846dcf796508bcd44512a58b.jpg?t=5cf00d8c20ff0", user_id: u2.id)
char32 = Character.create!(name: Faker::Games::ElderScrolls.first_name, gender: Faker::Gender.binary_type, background: "House Agent(Thuranni)", race: Faker::Games::ElderScrolls.race, strength: rand(1..20), dexterity: rand(1..20), constitution: rand(1..20), intelligence: rand(1..20), wisdom: rand(1..20), charisma: rand(1..20), picture: "https://i2.wp.com/www.nonzerosumgames.com/wp-content/uploads/2018/04/dwarf_stalker_by_shawcj-d6wpfv2.jpg", user_id: u3.id)
